tasks:
  - init: |
      echo "No special initialization"
    command: |
      composer install

image:
  file: .gitpod/Dockerfile

vscode:
  extensions:
    - ikappas.composer
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - getpsalm.psalm-vscode-plugin
    - SonarSource.sonarlint-vscode
    - recca0120.vscode-phpunit
